# Unstable Cuteness Calculator

The ludicrous Product Owner wants to use a data processor as crazy and unpredictable as they are!

They've has cobbled together a calculator to work out the cuteness level of a given `CuteAnimal`, but sometimes the animal is too damn cute for the calculator. 

We need to gracefully integrate this calculator to our OmniThingyParserâ„¢ but in a testable and stable manner. Because this calculator is wildly unpredictable, we need to mock the responses we get from it, but this time we need to handle exceptions too.

We know that the calculator will return a number for the cuteness, which we can return back to our main flow

*Example:*
```python
def test_calculate_cuteness_can_get_cuteness_value(cute_animal_steven):
    # Create the calculate_cuteness() method for testing
    with mock.patch("company_db.cuteness_calc.cuteness_age_adjustment") as mocker:
        mocker.return_value = 1

        expected = 1
        actual = calculate_cuteness(cute_animal=cute_animal_steven)
        assert actual == expected
```

We need to run a similar test, but showing the unhappy (or happy, depends how you look at it) path of having an `AnimalTooCuteException` thrown. Luckily we can mock this too!

*Example:*
```python
def test_calculate_cuteness_can_handle_exception(cute_animal_steven):
    # Refactor the calculate_cuteness() method for testing
    with mock.patch("company_db.cuteness_calc.cuteness_age_adjustment") as mocker:
        mocker.side_effect = AnimalTooCuteException()

        expected = "Animal too cute for calculator"
        actual = calculate_cuteness(cute_animal=cute_animal_steven)
        assert actual == expected
```